default:
  before_script:
    - |
      echo "pull project's workspace"
  tags:
    - project     #runner 注册的项目标签

linux_job:
  when: manual
  allow_failure: false
  script:
    - echo "测试linux runner"
  tags:
    - linux_test
  after_script:
    - | 
      echo "code to "$dir" end"
  except:
    - master
    


win_job1:
  variables:
    dir: "D:\\project\\workspace"
    project_addr: "git@10.10.10.31:java-g1/workspace.git"
  
  when: manual
  allow_failure: false
  script:                                 # 这是在windows  powershell下运行的
    - |
      cd $dir
      if ($(git rev-parse --abbrev-ref HEAD) -eq "dev") {
        echo "pull new version"
        echo "update dir "$dir" "
        git pull origin master
      }
      else {
        echo "Current Branch is $(git rev-parse --abbrev-ref HEAD)"                # git rev-parse --abbrev-ref HEAD 获取git当前目录下分支名
        echo "--------------- no update ---------------"
      }
   only:
    - master
